### PR TITLE
Optimize dbt execution on commands other than test

### PR DESCRIPTION
**Pull request by SOVALINUX**
Fix for https://github.com/EqualExperts/dbt-unit-testing/issues/56

//Sorry for delay with this one

### CODE REVIEW

**Comment by psousa50** [comment]
Hi @SOVALINUX, we think that the dbt *select* option should be enough as you mentioned. And thank you very much for your tip on the *flags.WHICH*, it can be handy sometime in the future 😄

**Comment by SOVALINUX** [comment]
Hi
Not sure I understand your point. Do you see any cases where it's harmful? Cause it by default improves performance of all commands where you don't need to run unit tests. But closing it looks for me like comment "we don't care about performance"

**Comment by cdiniz** [comment]
Hi @SOVALINUX 

We might have underestimated it. Our rationale was since the users have the control with 'select' and 'exclude', we don't need to do it on our side.

Let me have another conversation with @psousa50, and we'll give you an update.


Thank you for the feedback.

**Comment by cdiniz** [comment]
Closing due to inactivity and community support for the specific improvement.

Thank you for the collaboration.

**Pull request closed without merging**
