### PR TITLE
model that refs a model that refs a seed - fails test

### PR DESCRIPTION
**Pull request by gnilrets**
Here's an example of a model that fails if it depends on a model that depends on a seed.  I'm trying to work out a fix, but if you know anything quick that would be great!

```
Compilation Error in test covid_19_stats_country_model_using_seed_test (tests/unit/product/covid_19_stats_country_model_using_seed_test.sql)
  Source seed_test columns must be declared in sources.yml, or it must exist in database

  > in macro fake_source_sql (macros/test_helpers.sql)
  > called by macro build_model_complete_sql (macros/build_model_complete_sql.sql)
  > called by macro mock_input (macros/tests.sql)
  > called by macro mock_ref (macros/tests.sql)
  > called by macro test (macros/tests.sql)
  > called by test covid_19_stats_country_model_using_seed_test (tests/unit/product/covid_19_stats_country_model_using_seed_test.sql)
  > called by test covid_19_stats_country_model_using_seed_test (tests/unit/product/covid_19_stats_country_model_using_seed_test.sql)
```

### CODE REVIEW

**Comment by gnilrets** [comment]
@psousa50 - After submitting this, I noticed you've been working on the same thing today in another branch.  I added your changes here and my unit test is now passing!

**Comment by psousa50** [comment]
That's great 👍  @gnilrets, thanks!

**Comment by tnightengale** [comment]
We are also experiencing this problem and working on a fix! But I am very glad I glanced and found this PR 😄

**Review by cdiniz — APPROVED** [review]
thank you for you contribution!

**Pull request merged**
